name: CI_testing

on: [push]
# nice example: https://github.com/microsoft/vs-editor-api/blob/master/.github/workflows/main.yml

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, windows-2019]
        include:
          - os: ubuntu-18.04
            msbuild: dotnet msbuild
          - os: windows-latest
            msbuild: '"%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"'

    steps:
    - uses: actions/checkout@v1

    - name: Restore NuGet Packages
      run: |
        ${{ matrix.msbuild }} Frends.Community.LDAP.sln /noautoresponse /t:Restore /p:BuildTests=false
    - name: Build
      run: |
        ${{ matrix.msbuild }} Frends.Community.LDAP.sln /noautoresponse /t:Build /p:BuildTests=false
